/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AllCaption: typeof import('./src/components/dashboard/AllCaption.vue')['default']
    AllVideo: typeof import('./src/components/dashboard/AllVideo.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    CreateCaption: typeof import('./src/components/dashboard/CreateCaption.vue')['default']
    CreateVideo: typeof import('./src/components/dashboard/CreateVideo.vue')['default']
    DashboardSiderBar: typeof import('./src/components/bar/DashboardSiderBar.vue')['default']
    GenerateCaption: typeof import('./src/components/dashboard/GenerateCaption.vue')['default']
    GenerateVideo: typeof import('./src/components/dashboard/GenerateVideo.vue')['default']
    HeaderBar: typeof import('./src/components/bar/HeaderBar.vue')['default']
    HomeCard: typeof import('./src/components/card/HomeCard.vue')['default']
    IGridiconsCaption: typeof import('~icons/gridicons/caption')['default']
    IIconoirSidebarCollapse: typeof import('~icons/iconoir/sidebar-collapse')['default']
    IMaterialSymbolsLabProfileOutline: typeof import('~icons/material-symbols/lab-profile-outline')['default']
    IPhMoonBold: typeof import('~icons/ph/moon-bold')['default']
    IPhSunBold: typeof import('~icons/ph/sun-bold')['default']
    IPhUser: typeof import('~icons/ph/user')['default']
    IPhVideo: typeof import('~icons/ph/video')['default']
    IUilCreateDashboard: typeof import('~icons/uil/create-dashboard')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserPersona: typeof import('./src/components/dashboard/UserPersona.vue')['default']
    UserProfile: typeof import('./src/components/dashboard/UserProfile.vue')['default']
  }
}
